### ISSUE TITLE
Feedback bugs, features, etc

### ISSUE THREAD

**Issue by rmanaem** [neurobagel/query-tool#70]
Bugs:
- [x] neurobagel/old-query-tool#95
- [x] neurobagel/old-query-tool#96
- [x] neurobagel/old-query-tool#106 
- [x] neurobagel/old-query-tool#162 

Features:
- [ ] neurobagel/query-tool#55 
- [ ] neurobagel/query-tool#58 
- [ ] neurobagel/query-tool#64 
- [ ] neurobagel/query-tool#65 
- [ ] neurobagel/query-tool#66
- [x] neurobagel/old-query-tool#111 
- [ ] neurobagel/query-tool#67 
- [x] neurobagel/old-query-tool#128 
- [x] neurobagel/old-query-tool#141 
- [ ] neurobagel/query-tool#68 
- [ ] neurobagel/query-tool#69 

Other:
- [x] neurobagel/old-query-tool#163
